<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>OpenWu.CliLib</AssemblyName>
    <RootNamespace>OpenWu.CliLib</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\OpenWu.Core\OpenWu.Core.csproj" />
  </ItemGroup>

</Project>
