<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>openwu-cli</AssemblyName>
    <RootNamespace>OpenWu.Cli</RootNamespace>
    <ApplicationIcon>Assets\openwu.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\OpenWu.Core\OpenWu.Core.csproj" />
    <ProjectReference Include="..\OpenWu.CliLib\OpenWu.CliLib.csproj" />
  </ItemGroup>

</Project>
